[phases.setup]
nixPkgs = ["nodejs_22", "openssl_3"]

[phases.install]
cmds = ['npm install --include=dev', 'npx playwright install --with-deps chromium']

[phases.build]
cmds = ['npx prisma generate', 'npm run build']

[start]
cmd = 'npm start'
