-- Add new CRM pipeline stages: Agendado, Demo, Proposta
ALTER TYPE "LeadStatus" ADD VALUE IF NOT EXISTS 'SCHEDULED' AFTER 'SQL';
ALTER TYPE "LeadStatus" ADD VALUE IF NOT EXISTS 'DEMO' AFTER 'SCHEDULED';
ALTER TYPE "LeadStatus" ADD VALUE IF NOT EXISTS 'PROPOSAL' AFTER 'DEMO';
